import { BASE, checker, launch, shotPath } from './helpers.mjs'

const APP = BASE
const { check, finish } = checker()
const same = (a, b) => JSON.stringify(a) === JSON.stringify(b)

const browser = await launch()
const ctx = await browser.newContext({ viewport: { width: 1200, height: 800 }, colorScheme: 'light' })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message))
page.on('console', (m) => { if (m.type() === 'error') errors.push('console: ' + m.text()) })

// Helpers
const firstWords = () => page.locator('.msg .msg-text').allInnerTexts().then((t) => t.map((x) => x.split(' ')[0]))
const card = (text) => page.locator('.msg', { hasText: text })
const act = async (text, name) => { const c = card(text); await c.hover(); await c.getByRole('button', { name, exact: true }).click() }
const row = (name) => page.locator('.stream-list .stream-row', { has: page.locator('.stream-name', { hasText: new RegExp(`^${name}$`) }) })
const go = async (name, heading = name) => { await row(name).locator('.stream-btn').click(); await page.getByRole('heading', { name: heading, level: 2 }).waitFor() }
const count = (name) => row(name).locator('.stream-count').innerText().catch(() => '0')
const waitCount = (n) => page.waitForFunction((n) => document.querySelectorAll('.msg').length === n, n)
const post = async (target, text) => { const c = page.getByLabel(`Write to ${target}`); await c.fill(text); await c.press('Enter'); await card(text.split('\n')[0]).waitFor(); await page.waitForTimeout(10) }

// Pre-stable upgrade path: an older Dexie db (v1 => IDB version 10) with stale data must be wiped, not crash.
await page.goto(APP + '/pilefile-icon.svg')
await page.evaluate(() => new Promise((resolve, reject) => {
  const req = indexedDB.open('pilefile', 10)
  req.onupgradeneeded = () => {
    const d = req.result
    d.createObjectStore('streams', { keyPath: 'id' })
    const m = d.createObjectStore('messages', { keyPath: 'id' })
    m.createIndex('streamIds', 'streamIds', { multiEntry: true })
    d.createObjectStore('versions', { keyPath: 'id' })
  }
  req.onsuccess = () => {
    const d = req.result
    const tx = d.transaction(['messages', 'streams'], 'readwrite')
    tx.objectStore('messages').put({ id: 'old', text: 'legacy shape', streamIds: ['x'], words: ['legacy'], createdAt: 1, updatedAt: 1, versionCount: 1 })
    tx.objectStore('streams').put({ id: 'x', name: 'Legacy', createdAt: 1 })
    tx.oncomplete = () => { d.close(); resolve() }
    tx.onerror = () => reject(tx.error)
  }
  req.onerror = () => reject(req.error)
}))
errors.length = 0 // the raw SVG page above triggers a favicon.ico 404 that is unrelated to the app
await page.goto(APP)
await page.getByRole('heading', { name: 'Inbox', level: 2 }).waitFor()
await page.locator('.empty').waitFor()
check('old-schema database is wiped on open', (await page.locator('.msg').count()) === 0 && (await page.locator('.stream-list .stream-name').count()) === 2)

// Basic posting
await post('Inbox', 'Hello world first note')
const c0 = page.getByLabel('Write to Inbox')
await c0.type('Line one'); await c0.press('Shift+Enter'); await c0.type('Line two'); await c0.press('Enter')
await waitCount(2)
check('multi-line newest first', (await page.locator('.msg-text').first().innerText()) === 'Line one\nLine two')

// Streams + nesting
await page.getByRole('button', { name: 'New stream' }).click()
await page.getByLabel('New stream name').fill('Work'); await page.getByLabel('New stream name').press('Enter')
await page.getByRole('heading', { name: 'Work', level: 2 }).waitFor()
await post('Work', 'Quarterly budget review with the team')
await page.getByRole('button', { name: 'Nest new' }).click()
await page.getByLabel('New stream name').fill('Projects'); await page.getByLabel('New stream name').press('Enter')
await page.getByRole('heading', { name: 'Projects', level: 2 }).waitFor()
check('nested stream opens with breadcrumb', (await page.locator('.crumb-btn').allInnerTexts()).join('/') === 'Work')
await post('Projects', 'Project Alpha kickoff notes')
check('sidebar indents nested stream', parseInt(await row('Projects').evaluate((el) => el.style.paddingLeft)) > parseInt(await row('Work').evaluate((el) => el.style.paddingLeft)))
await page.waitForFunction(() => [...document.querySelectorAll('.stream-count')].some((e) => e.textContent === '4'))
check('counts roll up (Inbox 4, Work 2, Projects 1)', same([await count('Inbox'), await count('Work'), await count('Projects')], ['4', '2', '1']), `${await count('Inbox')} ${await count('Work')} ${await count('Projects')}`)

await go('Work')
await waitCount(2)
check('parent shows own + nested messages', same(await firstWords(), ['Project', 'Quarterly']))
check('nested message shows its stream chip', await card('Project Alpha').locator('.chip', { hasText: '#Projects' }).isVisible())
await page.screenshot({ path: shotPath('v3-parent-view.png') })
await card('Project Alpha').locator('.chip').click()
await page.getByRole('heading', { name: 'Projects', level: 2 }).waitFor()
check('chip navigates to the nested stream', true)
await page.locator('.crumb-btn', { hasText: 'Work' }).click()
await page.getByRole('heading', { name: 'Work', level: 2 }).waitFor()
check('breadcrumb navigates to parent', true)

// Collapse / expand
await row('Work').getByRole('button', { name: 'Collapse Work' }).click()
check('collapsing hides children', (await row('Projects').count()) === 0)
await row('Work').getByRole('button', { name: 'Expand Work' }).click()
check('expanding shows children again', (await row('Projects').count()) === 1)

// Move a message (single stream)
await go('Inbox')
await waitCount(4)
await act('Hello world', 'Move')
const radioTops = await card('Hello world').locator('.picker-row').evaluateAll((els) => els.map((e) => Math.round(e.getBoundingClientRect().top)))
check('move picker lists streams as stacked rows', radioTops.length >= 3 && radioTops.every((t, i) => i === 0 || t > radioTops[i - 1]), radioTops.join(','))
check('nested stream is indented in the picker', await card('Hello world').locator('.picker-row', { hasText: 'Projects' }).evaluate((e) => parseInt(e.style.paddingLeft) > 0))
await card('Hello world').getByRole('radio', { name: 'Projects' }).click()
await card('Hello world').locator('.chip', { hasText: '#Projects' }).waitFor()
check('moved message shows new stream chip, stays in Inbox', (await page.locator('.msg').count()) === 4)
check('radio reflects single membership', await card('Hello world').getByRole('radio', { name: 'Projects' }).isChecked())
await card('Hello world').getByRole('button', { name: 'Done' }).click()
await page.waitForFunction(() => [...document.querySelectorAll('.stream-count')].filter((e) => e.textContent === '2').length >= 1)
check('counts after move (Work 3, Projects 2)', same([await count('Work'), await count('Projects')], ['3', '2']), `${await count('Work')} ${await count('Projects')}`)

// Scoped pins
await go('Projects')
await waitCount(2)
check('Projects order before pin', same(await firstWords(), ['Project', 'Hello']))
await act('Hello world', 'Pin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Hello'))
check('pin in child puts it on top there', await card('Hello world').locator('.pin-badge', { hasText: /^Pinned$/ }).isVisible())

await go('Work')
await waitCount(3)
check('parent keeps chronological order for child pin', same(await firstWords(), ['Project', 'Quarterly', 'Hello']), (await firstWords()).join(','))
const badge = card('Hello world').locator('.pin-badge.elsewhere')
check('parent shows "pinned elsewhere" styling', (await badge.innerText()) === 'Pinned in Work › Projects' && (await card('Hello world').getAttribute('class')).includes('pinned'), await badge.innerText())
await page.screenshot({ path: shotPath('v3-pinned-elsewhere.png') })
await act('Hello world', 'Pin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Hello'))
check('pinning in parent too puts it on top there', await card('Hello world').locator('.pin-badge', { hasText: /^Pinned$/ }).isVisible())

await go('Inbox')
await waitCount(4)
check('inbox unaffected by stream pins', same(await firstWords(), ['Project', 'Quarterly', 'Line', 'Hello']), (await firstWords()).join(','))
check('inbox badge lists both contexts', (await card('Hello world').locator('.pin-badge.elsewhere').innerText()) === 'Pinned in Work, Work › Projects')
await act('Hello world', 'Pin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Hello'))
check('inbox pin (null context) puts it on top of inbox', true)
await page.waitForTimeout(20)
await act('Quarterly', 'Pin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Quarterly'))
await page.waitForTimeout(20)
await act('Hello world', 'Re-pin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Hello'))
check('re-pin bubbles above later pin', same(await firstWords(), ['Hello', 'Quarterly', 'Project', 'Line']))
await act('Hello world', 'Unpin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Quarterly'))
check('unpin here keeps other-context pin styling', (await card('Hello world').locator('.pin-badge.elsewhere').count()) === 1 && same(await firstWords(), ['Quarterly', 'Project', 'Line', 'Hello']))

// Moving a message out of its stream drops pins that no longer apply
await act('Hello world', 'Move')
await card('Hello world').getByRole('radio', { name: 'No stream' }).click()
await page.waitForFunction(() => !document.querySelector('.msg:nth-last-child(1) .chip'))
await card('Hello world').getByRole('button', { name: 'Done' }).click()
check('moving to no stream drops stream-scoped pins', (await card('Hello world').locator('.pin-badge').count()) === 0)
await act('Quarterly', 'Unpin')

// Move a stream in the tree
await go('Projects')
await page.locator('header').getByRole('button', { name: 'Move' }).click()
await page.locator('#move-parent').selectOption('')
await page.waitForFunction(() => document.querySelectorAll('.crumb-btn').length === 0)
check('stream moved to top level loses breadcrumb', true)
await page.waitForFunction(() => [...document.querySelectorAll('.stream-count')].some((e) => e.textContent === '1'))
check('parent count drops after child moves out', (await count('Work')) === '1')
await page.locator('header').getByRole('button', { name: 'Move' }).click()
const options = await page.locator('#move-parent option').allInnerTexts()
check('move options exclude the stream itself', !options.some((o) => o.trim() === 'Projects'))
await page.locator('#move-parent').selectOption({ label: 'Work' })
await page.locator('.crumb-btn', { hasText: 'Work' }).waitFor()
check('stream moved back under Work', true)

// In-stream search (Work holds Quarterly; Projects under it holds Alpha)
await go('Work')
await waitCount(2)
await page.locator('header').getByRole('button', { name: 'Search' }).click()
const inStream = page.getByRole('searchbox', { name: 'Search in Work' })
await inStream.waitFor()
check('in-stream search replaces composer', (await page.locator('.composer').count()) === 0)
await inStream.fill('alpha')
await waitCount(1)
check('in-stream search includes nested streams', await card('Project Alpha').locator('.chip', { hasText: '#Projects' }).isVisible())
check('in-stream match is highlighted', (await card('Project Alpha').locator('.msg-text mark').innerText()) === 'Alpha')
check('in-stream count label', (await page.locator('.stream-search-count').innerText()) === '1 of 2')
await page.screenshot({ path: shotPath('v3-in-stream-search.png') })
await inStream.fill('quar bud')
await waitCount(1)
check('in-stream multi-term prefix match', await card('Quarterly').isVisible())
await inStream.fill('zzz')
await page.locator('.empty', { hasText: 'No matches' }).waitFor()
check('in-stream empty state mentions nested streams', (await page.locator('.empty').innerText()).includes('or its nested streams'))
await inStream.press('Escape')
await page.locator('.composer').waitFor()
await waitCount(2)
check('Escape closes in-stream search and restores list', true)
await go('Inbox')
await page.locator('header').getByRole('button', { name: 'Search' }).click()
await page.getByRole('searchbox', { name: 'Search in Inbox' }).fill('line')
await waitCount(1)
check('inbox in-stream search works', (await page.locator('.msg-text').innerText()).startsWith('Line one'))
await go('Projects')
check('switching streams closes in-stream search', (await page.locator('.stream-search').count()) === 0)

// Search shows paths
const search = page.getByRole('searchbox', { name: 'Search' })
await search.fill('alpha')
await page.locator('.result-row').first().waitFor()
check('search result shows stream path', (await page.locator('.result-meta').first().innerText()).includes('Work › Projects'))
await search.fill('proj')
await page.locator('.results .stream-row').first().waitFor()
check('stream search shows path', (await page.locator('.results .stream-name').first().innerText()) === 'Work › Projects')
await search.fill('')

// Rename then delete a nested stream: contents move up to the parent
await page.getByRole('button', { name: 'Rename' }).click()
await page.getByLabel('Stream name').fill('Ideas'); await page.getByLabel('Stream name').press('Enter')
await page.getByRole('heading', { name: 'Ideas', level: 2 }).waitFor()
page.once('dialog', (d) => { check('delete dialog mentions destination', d.message().includes('move up to "Work"')); d.accept() })
await page.getByRole('button', { name: 'Delete' }).first().click()
await page.getByRole('heading', { name: 'Inbox', level: 2 }).waitFor()
await go('Work')
await waitCount(2)
check('deleted stream\'s messages moved to parent', same(await firstWords(), ['Project', 'Quarterly']) && (await page.locator('.chip').count()) === 0)

// Persistence
await act('Quarterly', 'Pin')
await page.waitForFunction(() => document.querySelector('.msg .msg-text')?.textContent?.startsWith('Quarterly'))
await page.reload()
await page.getByRole('heading', { name: 'Inbox', level: 2 }).waitFor()
await go('Work')
await waitCount(2)
check('pins and tree persist across reload', same(await firstWords(), ['Quarterly', 'Project']) && (await page.locator('.stream-list .stream-name').allInnerTexts()).join(',') === 'Inbox,All,Work')

// Markdown rendering
await go('Inbox')
const md = page.getByLabel('Write to Inbox')
const mdText = '## Heading\n**Bold** and _italic_, a [link](https://example.com), `code`, ~~gone~~\nnext line\n- item one\n- [ ] task\n\n```\nblock\n```\n<script>alert(1)</script>'
await md.fill(mdText)
await md.press('Enter')
const mdCard = card('Heading')
await mdCard.waitFor()
const q = (sel) => mdCard.locator('.md ' + sel).count()
check('markdown: heading, strong, em, code, del', (await q('h2')) === 1 && (await q('strong')) === 1 && (await q('em')) === 1 && (await q('code')) === 2 && (await q('del')) === 1)
check('markdown: link opens in new tab safely', (await mdCard.locator('.md a').getAttribute('target')) === '_blank' && (await mdCard.locator('.md a').getAttribute('rel')) === 'noopener noreferrer')
check('markdown: single newline is a line break', (await q('br')) >= 1)
check('markdown: list and task checkbox', (await q('li')) === 2 && (await q('li input[type=checkbox]')) === 1)
check('markdown: fenced code block', (await q('pre code')) === 1)
check('markdown: raw html is not executed', (await q('script')) === 0)
check('markdown: no stray blank lines from block whitespace', (await mdCard.locator('.md').evaluate((el) => el.getBoundingClientRect().height)) < 320)
await page.locator('header').getByRole('button', { name: 'Search' }).click()
await page.getByRole('searchbox', { name: 'Search in Inbox' }).fill('bold')
await waitCount(1)
check('markdown: search highlight inside strong', (await mdCard.locator('.md strong mark').innerText()) === 'Bold')
await page.screenshot({ path: shotPath('v3-markdown.png') })
await page.getByRole('searchbox', { name: 'Search in Inbox' }).press('Escape')
await page.locator('.composer').waitFor()
await mdCard.hover()
await mdCard.getByRole('button', { name: 'Edit' }).click()
check('markdown: edit shows raw source', (await mdCard.getByLabel('Edit message').inputValue()) === mdText)
await mdCard.getByLabel('Edit message').press('Escape')

// Ordering by creation time: editing the oldest message does not move it
const beforeEdit = await firstWords()
await act('Hello world', 'Edit')
const ed = card('Hello world').getByLabel('Edit message')
await ed.press('End'); await ed.type(' (touched)'); await ed.press('Enter')
await card('Hello world').locator('time', { hasText: 'edited' }).waitFor()
check('edited message keeps its place', same(await firstWords(), beforeEdit), (await firstWords()).join(','))
check('edited message shows both timestamps', true)
await page.locator('header').getByRole('button', { name: 'Search' }).click()
await page.getByRole('searchbox', { name: 'Search in Inbox' }).fill('note')
await page.waitForFunction(() => document.querySelectorAll('.msg').length > 1)
check('in-stream search orders by creation too', (await page.locator('.msg .msg-text').last().innerText()).startsWith('Hello'))
await page.getByRole('searchbox', { name: 'Search in Inbox' }).press('Escape')
await page.locator('.composer').waitFor()

// Mobile drawer
await page.setViewportSize({ width: 390, height: 844 })
await page.waitForTimeout(300)
const sb = await page.locator('.sidebar').boundingBox()
check('sidebar hidden on mobile', sb && sb.x + sb.width <= 1)
await page.getByRole('button', { name: 'Open streams' }).click()
await page.waitForTimeout(300)
check('drawer opens', (await page.locator('.sidebar').boundingBox()).x === 0)
await page.screenshot({ path: shotPath('v3-mobile-drawer.png') })
await row('Inbox').locator('.stream-btn').click()
await page.waitForTimeout(300)
const sb2 = await page.locator('.sidebar').boundingBox()
check('drawer closes on selection', sb2 && sb2.x + sb2.width <= 1)

check('no console/page errors', errors.length === 0, errors.join(' | '))
await finish(browser)
