import { BASE, checker, launch, shotPath } from './helpers.mjs'
const { check, finish } = checker()
const browser = await launch()
const page = await (await browser.newContext({ viewport: { width: 1200, height: 800 } })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message)); page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto(BASE)
const card = (t) => page.locator('.msg', { has: page.locator('.msg-text', { hasText: t }) })
const row = (name) => page.locator('.stream-list .stream-row', { has: page.locator('.stream-name', { hasText: new RegExp(`^${name}$`) }) })
const go = async (name) => { await row(name).locator('.stream-btn').click(); await page.getByRole('heading', { name, level: 2 }).waitFor() }
const act = async (t, name) => { await card(t).hover(); await card(t).getByRole('button', { name, exact: true }).click() }
const waitCount = (n) => page.waitForFunction((n) => document.querySelectorAll('.msg').length === n, n)
/** Waits for a sidebar row's unread badge to read `n`; 0 means no badge at all. */
const waitUnread = (name, n) => n === 0 ? row(name).locator('.stream-count').waitFor({ state: 'detached' }) : row(name).locator('.stream-count', { hasText: new RegExp(`^${n}$`) }).waitFor()
const unreadBadges = (name) => row(name).locator('.stream-count').count()
const move = async (t, to) => { await act(t, 'Move'); await card(t).getByRole('radio', { name: to }).click() }
const newStream = async (name) => { await page.getByRole('button', { name: 'New stream' }).click(); await page.getByLabel('New stream name').fill(name); await page.getByLabel('New stream name').press('Enter'); await page.getByRole('heading', { name, level: 2 }).waitFor() }
const post = async (target, text) => { const c = page.getByLabel(`Write to ${target}`); await c.fill(text); await c.press('Enter'); await card(text).waitFor() }
const header = page.locator('header')
const markAll = header.getByRole('button', { name: 'Mark all as read' })
const unreadOnly = header.getByRole('button', { name: 'Unread only' })
const texts = () => page.locator('.msg .msg-text').allInnerTexts()
const acceptNext = () => { let text = ''; page.once('dialog', (d) => { text = d.message(); d.accept() }); return () => text }

await page.getByRole('heading', { level: 2 }).waitFor()
check('All is the landing view', (await page.getByRole('heading', { level: 2 }).innerText()) === 'All')
check('sidebar lists All then Inbox', (await page.locator('.stream-list .stream-name').allInnerTexts()).join(',') === 'All,Inbox')
check('mark-all disabled when there is nothing unread', await markAll.isDisabled())
await go('Inbox')
check('Inbox opens with the unread filter on, and mark-all disabled while empty', (await markAll.isDisabled()) && (await unreadOnly.getAttribute('aria-pressed')) === 'true')
check('empty inbox says caught up', (await page.locator('.empty').innerText()).includes('caught up'))

await newStream('Work')
await post('Work', 'In work')
await go('Inbox')
await post('Inbox', 'Loose note')
await post('Inbox', 'Another scrap')
await waitCount(2)
check('Inbox collects unfiled messages only, not ones written into a stream', (await card('In work').count()) === 0)
check('unread cards show a dot', (await page.locator('.msg .unread-dot').count()) === 2 && (await page.locator('.msg.unread').count()) === 2)
await waitUnread('Inbox', 2)
await waitUnread('Work', 1)
check('sidebar shows unread counts for the Inbox and each stream, none for All', (await unreadBadges('All')) === 0)
await page.screenshot({ path: shotPath('v7-inbox.png') })

// Mark read in Inbox removes the card
await act('Loose note', 'Mark read')
await waitCount(1)
check('Mark read removes it from the Inbox', (await card('Loose note').count()) === 0)
await waitUnread('Inbox', 1)
check('Inbox count drops', (await page.locator('.main-count').innerText()) === '1 unread')

// The Inbox's unread filter can be switched off to see every unfiled message
await unreadOnly.click()
await waitCount(2)
check('Inbox with the filter off lists read unfiled messages too, still nothing filed in a stream', (await texts()).join(',') === 'Another scrap,Loose note' && (await page.locator('.main-count').innerText()) === '2 messages')
check('the Inbox badge still counts only unread', (await row('Inbox').locator('.stream-count').innerText()) === '1')
await page.screenshot({ path: shotPath('v9-inbox-all-unfiled.png') })
await go('Work')
await go('Inbox')
await waitCount(2)
check('the Inbox remembers the filter was switched off', (await unreadOnly.getAttribute('aria-pressed')) !== 'true')
await unreadOnly.click()
await waitCount(1)
check('switching it back on returns the Inbox to unread only', (await texts()).join(',') === 'Another scrap')
await go('All')
await waitCount(3)
check('All keeps every message', true)
check('read card has no dot and offers Mark unread', (await card('Loose note').locator('.unread-dot').count()) === 0 && (await card('Loose note').getByRole('button', { name: 'Mark unread' }).count()) === 1)
check('message written into a stream is still unread in All', (await card('In work').locator('.unread-dot').count()) === 1)
check('stream chip visible in All for filed message', await card('In work').locator('.chip', { hasText: '#Work' }).isVisible())

// Unread-only filter
check('filter starts off', (await unreadOnly.getAttribute('aria-pressed')) !== 'true' && (await page.locator('.main-count').innerText()) === '3 messages')
await unreadOnly.click()
await waitCount(2)
check('unread-only hides read messages', (await texts()).join(',') === 'Another scrap,In work' && (await unreadOnly.getAttribute('aria-pressed')) === 'true')
check('header counts the unread ones while filtering', (await page.locator('.main-count').innerText()) === '2 unread')
await page.screenshot({ path: shotPath('v8-unread-only.png') })
await act('Another scrap', 'Mark read')
await waitCount(1)
check('marking read under the filter removes the card', (await texts()).join(',') === 'In work')
await go('Work')
check('the filter is per view: Work still shows everything', (await unreadOnly.getAttribute('aria-pressed')) !== 'true')
await go('All')
await waitCount(1)
check('and All remembers it', (await unreadOnly.getAttribute('aria-pressed')) === 'true')
await page.getByRole('searchbox', { name: 'Search' }).fill('loose')
await page.locator('.result-row').first().click()
await waitCount(2)
check('a read message opened from search is still shown under the filter', (await card('Loose note').count()) === 1)
await page.getByRole('searchbox', { name: 'Search' }).fill('')
await go('Work')
await go('All')
await waitCount(1)
check('once you navigate away the filter is strict again', (await texts()).join(',') === 'In work')
await act('In work', 'Mark read')
await page.locator('.empty').waitFor()
check('filter with nothing unread says so', (await page.locator('.empty').innerText()).includes('No unread messages') && (await markAll.isDisabled()))
await unreadOnly.click()
await waitCount(3)
check('switching the filter off brings everything back', (await page.locator('.unread-dot').count()) === 0)
await waitUnread('Inbox', 0)
await waitUnread('Work', 0)
check('badges disappear at zero', true)

// Read state inside a stream: the dot and the stream's count toggle, the Inbox is not involved
await go('Work')
await act('In work', 'Mark unread')
await card('In work').locator('.unread-dot').waitFor()
await waitUnread('Work', 1)
check('stream view: mark unread brings the dot and the count back, not the Inbox', (await unreadBadges('Inbox')) === 0)
await act('In work', 'Mark read')
await page.waitForFunction(() => !document.querySelector('.msg .unread-dot'))
await waitUnread('Work', 0)
check('stream view: mark read keeps the card, clears dot and count', (await card('In work').count()) === 1)
await act('In work', 'Mark unread')
await waitUnread('Work', 1)

// Filing an Inbox message takes it out; unfiling brings it back while unread
await go('All')
await act('Another scrap', 'Mark unread')
await go('Inbox')
await waitCount(1)
await act('Another scrap', 'Pin')
await card('Another scrap').locator('.pin-badge', { hasText: /^Pinned$/ }).waitFor()
await move('Another scrap', 'Work')
await page.locator('.empty').waitFor()
check('moving a message into a stream removes it from the Inbox', (await page.locator('.msg').count()) === 0)
await waitUnread('Inbox', 0)
await waitUnread('Work', 2)
check('its unread count moves from the Inbox to the stream', true)
await go('Work')
await waitCount(2)
check('filed message is still unread in its stream', (await card('Another scrap').locator('.unread-dot').count()) === 1)
check('filing drops the Inbox pin', (await card('Another scrap').locator('.pin-badge').count()) === 0)
await move('Another scrap', 'No stream')
await waitCount(1)
await waitUnread('Inbox', 1)
check('moving it back to no stream returns it to the Inbox', true)

// Editing a read message leaves it read
await go('All')
await act('Loose note', 'Edit')
const ed = page.getByLabel('Edit message'); await ed.press('End'); await ed.type(' edited'); await ed.press('Enter')
await card('Loose note').locator('time', { hasText: 'edited' }).waitFor()
check('editing content keeps it read', (await card('Loose note').locator('.unread-dot').count()) === 0 && (await row('Inbox').locator('.stream-count').innerText()) === '1')
await act('Loose note', 'Mark unread')
await waitUnread('Inbox', 2)
check('marking an unfiled message unread returns it to the Inbox', true)

// Mark all as read with confirmation: only what the view shows
await go('Inbox')
await waitCount(2)
let dialogText = ''
page.once('dialog', (d) => { dialogText = d.message(); d.dismiss() })
await markAll.click()
await page.waitForTimeout(100)
check('confirmation names the count', dialogText === 'Mark 2 messages as read?', dialogText)
check('dismissing keeps the Inbox', (await page.locator('.msg').count()) === 2)
page.once('dialog', (d) => d.accept())
await markAll.click()
await page.locator('.empty').waitFor()
check('accepting clears the Inbox', (await page.locator('.msg').count()) === 0)
await go('All')
await waitCount(3)
check('All unaffected; only the message filed in a stream is still unread', (await page.locator('.unread-dot').count()) === 1 && (await card('In work').locator('.unread-dot').count()) === 1)

// Mark all as read in a stream covers its nested streams, and nothing outside it
await go('Work')
await header.getByRole('button', { name: 'Nest new' }).click()
await page.getByLabel('New stream name').fill('Projects'); await page.getByLabel('New stream name').press('Enter')
await page.getByRole('heading', { name: 'Projects', level: 2 }).waitFor()
await post('Projects', 'Nested plan')
await newStream('Home')
await post('Home', 'Buy milk')
await post('Home', 'Fix the tap')
await go('All')
await post('All', 'Stray thought')
await waitUnread('Work', 2)
await waitUnread('Projects', 1)
await waitUnread('Home', 2)
await waitUnread('Inbox', 1)
check('unread counts roll nested streams up into the parent', true)
await page.screenshot({ path: shotPath('v8-unread-counts.png') })
await go('Work')
await waitCount(2)
let said = acceptNext()
await markAll.click()
await page.waitForFunction(() => !document.querySelector('.msg .unread-dot'))
check('stream mark-all confirms with the count it can see', said() === 'Mark 2 messages as read?', said())
await waitUnread('Work', 0)
await waitUnread('Projects', 0)
check('stream mark-all clears the stream and its nested streams', (await page.locator('.msg').count()) === 2 && (await markAll.isDisabled()))
check('stream mark-all leaves other streams and the Inbox alone', (await row('Home').locator('.stream-count').innerText()) === '2' && (await row('Inbox').locator('.stream-count').innerText()) === '1')

// With a search active, mark-all only covers the matches
await go('Home')
await header.getByRole('button', { name: 'Search' }).click()
await page.getByRole('searchbox', { name: 'Search in Home' }).fill('milk')
await waitCount(1)
said = acceptNext()
await markAll.click()
await waitUnread('Home', 1)
check('mark-all during a search marks only the matches', said() === 'Mark 1 message as read?', said())
await page.getByRole('searchbox', { name: 'Search in Home' }).press('Escape')
await waitCount(2)
check('the message outside the search is still unread', (await card('Fix the tap').locator('.unread-dot').count()) === 1 && (await card('Buy milk').locator('.unread-dot').count()) === 0)

// Mark all as read in All clears everything
await go('All')
await page.waitForFunction(() => document.querySelectorAll('.msg .unread-dot').length === 2)
said = acceptNext()
await markAll.click()
await page.waitForFunction(() => !document.querySelector('.msg .unread-dot'))
check('All mark-all covers every unread message', said() === 'Mark 2 messages as read?', said())
await waitUnread('Home', 0)
await waitUnread('Inbox', 0)
check('no unread counts left anywhere', (await page.locator('.stream-list .stream-count').count()) === 0)

// Task checkbox toggle does not change read state
const ca = page.getByLabel('Write to All'); await ca.fill('- [ ] follow up'); await ca.press('Enter'); await card('follow up').waitFor()
await waitUnread('Inbox', 1)
check('posting from All lands in Inbox', true)
await act('follow up', 'Mark read')
await waitUnread('Inbox', 0)
await card('follow up').locator('input[type=checkbox]').click()
await card('follow up').locator('time', { hasText: 'edited' }).waitFor()
check('ticking a task keeps it read', (await card('follow up').locator('.unread-dot').count()) === 0 && (await unreadBadges('Inbox')) === 0)

// Search result for an unfiled read message opens All
await go('Work')
await page.getByRole('searchbox', { name: 'Search' }).fill('loose')
await page.locator('.result-row').first().click()
await page.getByRole('heading', { name: 'All', level: 2 }).waitFor()
check('search result for unfiled message opens All', true)
await page.getByRole('searchbox', { name: 'Search' }).fill('')

// Narrow screens: the stream's own actions fold into one sheet so the header keeps room for the title
await page.setViewportSize({ width: 390, height: 844 })
await page.waitForTimeout(300)
await page.getByRole('button', { name: 'Open streams' }).click()
await row('Projects').locator('.stream-btn').click()
await page.getByRole('heading', { name: 'Projects', level: 2 }).waitFor()
await page.waitForTimeout(300)
const fits = await page.evaluate(() => { const t = document.querySelector('.main-title'); return { doc: document.documentElement.scrollWidth, win: innerWidth, last: Math.round(document.querySelector('.head-actions')?.lastElementChild?.getBoundingClientRect().right ?? 0), clipped: t.scrollWidth > t.clientWidth } })
check('narrow stream header fits the screen without clipping the title', fits.doc <= fits.win && fits.last <= fits.win && !fits.clipped, JSON.stringify(fits))
check('narrow header keeps Search, Unread only and Mark all, and folds the rest into Stream actions', (await page.locator('.head-actions button').count()) === 4 && (await header.getByRole('button', { name: 'Rename' }).count()) === 0 && (await unreadOnly.count()) === 1 && (await markAll.count()) === 1)
await page.screenshot({ path: shotPath('v8-narrow-header.png') })
await header.getByRole('button', { name: 'Stream actions' }).click()
const sheet = page.locator('dialog.sheet')
await sheet.waitFor()
check('stream sheet lists rename, nest, move and delete', (await sheet.locator('.sheet-label').allInnerTexts()).join('|') === 'Rename stream|New stream inside this one|Move stream under another|Delete stream')
await page.screenshot({ path: shotPath('v8-stream-sheet.png') })
await sheet.getByRole('button', { name: 'Rename stream' }).click()
await sheet.waitFor({ state: 'detached' })
const nameField = page.getByLabel('Stream name')
await nameField.waitFor()
check('rename from the sheet opens the focused name field', await nameField.evaluate((el) => document.activeElement === el))
await nameField.fill('Plans'); await nameField.press('Enter')
await page.getByRole('heading', { name: 'Plans', level: 2 }).waitFor()
check('rename from the sheet applies', true)
await header.getByRole('button', { name: 'Stream actions' }).click()
await sheet.getByRole('button', { name: 'Move stream under another' }).click()
await page.locator('#move-parent').waitFor()
check('move from the sheet opens the parent picker', (await page.locator('#move-parent option').allInnerTexts()).map((o) => o.trim()).join('|') === 'Top level|Home|Work')
await page.locator('#move-parent').selectOption({ label: 'Home' })
await page.locator('.crumb-btn', { hasText: 'Home' }).waitFor()
check('move from the sheet applies', true)

check('no console errors', errors.length === 0, errors.join(' | '))
await finish(browser)
