import { BASE, checker, launch, shotPath } from './helpers.mjs'
const { check, finish } = checker()
const browser = await launch()
const page = await (await browser.newContext({ viewport: { width: 1200, height: 800 } })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message)); page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto(BASE)
const c = page.getByLabel('Write to All')
const post = async (t) => { await c.fill(t); await c.press('Enter'); await page.waitForTimeout(25) }
await post('Budget review #Work')
await post('lunch notes #work #Food')
await post('Working late #Working')
await post('# Not a tag\n`#fff` in code and C# language, see example.com/#frag')
await post('Check out #MyTag')
await page.waitForFunction(() => document.querySelectorAll('.msg').length === 5)
const card = (t) => page.locator('.msg', { hasText: t })
check('tags render as buttons', (await card('Budget').locator('button.tag').innerText()) === '#Work')
check('heading, code, C#, and URL fragment are not tags', (await card('Not a tag').locator('button.tag').count()) === 0 && (await card('Not a tag').locator('h1').count()) === 1)
check('two tags on one message', (await card('lunch').locator('button.tag').allInnerTexts()).join(',') === '#work,#Food')

// Click a tag -> sidebar search opens with it
await card('Budget').locator('button.tag').click()
const sb = page.getByRole('searchbox', { name: 'Search' })
check('clicking a tag fills the sidebar search', (await sb.inputValue()) === '#Work ')
check('no menu after a tag click', (await page.locator('#sidebar-tag-menu').count()) === 0)
check('sidebar search box is focused', await sb.evaluate((el) => document.activeElement === el))
await page.locator('.result-row').first().waitFor()
const rows = () => page.locator('.result-row .result-text').allInnerTexts()
check('tag search is exact but case-insensitive (#Work finds #work, not #Working)', JSON.stringify((await rows()).map((r) => r.split(' ')[0]).sort()) === '["Budget","lunch"]', JSON.stringify(await rows()))
check('tag is highlighted in results', (await page.locator('.result-row mark').first().innerText()).toLowerCase() === '#work')

await sb.fill('#MyTa')
await page.locator('text=No matching messages').waitFor()
check('partial tag does not match', true)
await sb.fill('#MyTag')
await page.locator('.result-row').first().waitFor()
check('full tag matches', (await page.locator('.result-row').count()) === 1)
check('menu hidden when typed tag is the only exact match', (await page.locator('#sidebar-tag-menu').count()) === 0)
await sb.fill('#work lunch')
await page.waitForFunction(() => document.querySelectorAll('.result-row').length === 1)
check('tag combined with word prefix', (await rows())[0].startsWith('lunch'))
await sb.fill('#Food budget')
await page.locator('text=No matching messages').waitFor()
check('tag AND word that is absent yields nothing', true)

// Suggestion menu in the sidebar
await sb.fill('#wo')
const menu = page.locator('#sidebar-tag-menu')
await menu.waitFor()
check('typing #wo lists Work and Working with counts', (await menu.locator('li').allInnerTexts()).map((t) => t.replace(/\s+/g, ' ')).join('|') === '#Work 2|#Working 1', (await menu.locator('li').allInnerTexts()).join('|'))
check('no suggestion for plain words', true)
await sb.press('ArrowDown')
check('arrow moves the highlight', (await menu.locator('li.active').innerText()).startsWith('#Working'))
await sb.press('Enter')
check('Enter picks the tag and adds a space', (await sb.inputValue()) === '#Working ')
await page.waitForFunction(() => document.querySelectorAll('.result-row').length === 1)
check('picked tag searches immediately', (await rows())[0].startsWith('Working'))
check('menu closes after pick', (await menu.count()) === 0)
await sb.fill('#x')
await page.waitForTimeout(100)
check('no menu when nothing matches', (await menu.count()) === 0)
await sb.fill('#')
await menu.waitFor()
check('bare # lists every tag, most used first', (await menu.locator('li .tag-menu-name').allInnerTexts()).join(',') === '#Work,#Food,#MyTag,#Working', (await menu.locator('li .tag-menu-name').allInnerTexts()).join(','))
await sb.press('Escape')
check('Escape closes the menu but keeps the query', (await menu.count()) === 0 && (await sb.inputValue()) === '#')
await sb.press('Escape')
check('second Escape clears the query', (await sb.inputValue()) === '')
await page.locator('.stream-list').waitFor()

// Suggestion menu in in-stream search, picked with the mouse
await page.locator('header').getByRole('button', { name: 'Search' }).click()
const inS = page.getByRole('searchbox', { name: 'Search in All' })
await inS.type('notes #f')
const menu2 = page.locator('#stream-tag-menu')
await menu2.waitFor()
check('in-stream menu filters by the current token only', (await menu2.locator('li').count()) === 1)
await menu2.locator('li').first().click()
check('mouse pick replaces just the # token', (await inS.inputValue()) === 'notes #Food ')
await page.waitForFunction(() => document.querySelectorAll('.msg').length === 1)
check('in-stream tag+word filter', await card('lunch').isVisible())
check('in-stream tag highlighted in card', (await card('lunch').locator('mark').allInnerTexts()).join(',').toLowerCase().includes('#food'))
await inS.press('Escape')
await page.locator('.composer').waitFor()

// Removing a tag from the only message using it drops it from suggestions
await card('lunch').hover(); await card('lunch').getByRole('button', { name: 'Edit' }).click()
await card('lunch').getByLabel('Edit message').fill('lunch notes #work')
await card('lunch').getByLabel('Edit message').press('Enter')
await card('lunch').locator('time', { hasText: 'edited' }).waitFor()
await sb.fill('#f')
await page.waitForTimeout(150)
check('unused tag disappears from suggestions', (await menu.count()) === 0)
await sb.fill('')

// Mobile: tag click opens the drawer
await page.setViewportSize({ width: 390, height: 844 })
await page.waitForTimeout(300)
await card('Check out').locator('button.tag').click()
await page.waitForTimeout(350)
check('on mobile a tag click opens the drawer with the search', (await page.locator('.sidebar').boundingBox()).x === 0 && (await sb.inputValue()) === '#MyTag ')
await page.screenshot({ path: shotPath('v5-tags-mobile.png') })
check('no console errors', errors.length === 0, errors.join(' | '))
await finish(browser)
