import { BASE, checker, launch, shotPath } from './helpers.mjs'
const { check, finish } = checker()
const browser = await launch()
const page = await (await browser.newContext({ viewport: { width: 1200, height: 800 } })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message)); page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
await page.goto(BASE)
const card = (t) => page.locator('.msg', { has: page.locator('.msg-text', { hasText: t }) })
const row = (name) => page.locator('.stream-list .stream-row', { has: page.locator('.stream-name', { hasText: new RegExp(`^${name}$`) }) })
const go = async (name) => { await row(name).locator('.stream-btn').click(); await page.getByRole('heading', { name, level: 2 }).waitFor() }
const animating = (loc) => loc.evaluate((el) => el.getAnimations().length > 0)

// Streams: Work > Projects, and Other
await page.getByRole('button', { name: 'New stream' }).click()
await page.getByLabel('New stream name').fill('Work'); await page.getByLabel('New stream name').press('Enter')
await page.getByRole('heading', { name: 'Work', level: 2 }).waitFor()
await page.locator('header').getByRole('button', { name: 'Nest new' }).click()
await page.getByLabel('New stream name').fill('Projects'); await page.getByLabel('New stream name').press('Enter')
await page.getByRole('heading', { name: 'Projects', level: 2 }).waitFor()
const cp = page.getByLabel('Write to Projects')
await cp.fill('**Original** plan with a [link](https://x.y) and `code`'); await cp.press('Enter')
await card('Original').waitFor()
await page.getByRole('button', { name: 'New stream' }).click()
await page.getByLabel('New stream name').fill('Other'); await page.getByLabel('New stream name').press('Enter')
await page.getByRole('heading', { name: 'Other', level: 2 }).waitFor()

// Reply within Work (parent shows Projects' message)
await go('Work')
await card('Original').waitFor()
await card('Original').hover(); await card('Original').getByRole('button', { name: 'Reply' }).click()
const composerQuote = page.locator('.composer .quote')
await composerQuote.waitFor()
check('quote appears above the composer', true)
check('quote shows plain text of the original', (await composerQuote.locator('.quote-text').innerText()) === 'Original plan with a link and code')
check('composer focused on reply', await page.getByLabel('Write to Work').evaluate((el) => document.activeElement === el))
await composerQuote.getByRole('button', { name: 'Cancel reply' }).click()
check('cancel removes the quote', (await composerQuote.count()) === 0)
await card('Original').hover(); await card('Original').getByRole('button', { name: 'Reply' }).click()
await composerQuote.waitFor()
const cw = page.getByLabel('Write to Work')
await cw.fill('First reply'); await cw.press('Enter')
await card('First reply').waitFor()
check('quote cleared after posting', (await composerQuote.count()) === 0)
const replyQuote = card('First reply').locator('.quote')
check('reply shows the quote of the original', (await replyQuote.locator('.quote-text').innerText()) === 'Original plan with a link and code')
await replyQuote.locator('button.quote-body').click()
await page.waitForTimeout(100)
check('clicking the quote stays in Work and highlights the original', (await page.getByRole('heading', { level: 2 }).innerText()) === 'Work' && (await animating(card('Original'))))

// Reply from All, then move the reply to Other: clicking the quote navigates to Projects
await go('All')
await card('Original').hover(); await card('Original').getByRole('button', { name: 'Reply' }).click()
const ci = page.getByLabel('Write to All')
await ci.fill('Reply from all'); await ci.press('Enter')
await card('Reply from all').waitFor()
await card('Reply from all').hover(); await card('Reply from all').getByRole('button', { name: 'Move' }).click()
await card('Reply from all').getByRole('radio', { name: 'Other' }).click()
await card('Reply from all').locator('.chip', { hasText: '#Other' }).waitFor()
await card('Reply from all').getByRole('button', { name: 'Done' }).click()
await go('Other')
await card('Reply from all').locator('button.quote-body').click()
await page.getByRole('heading', { name: 'Projects', level: 2 }).waitFor()
await page.waitForTimeout(100)
check('quote to a message elsewhere opens its stream and highlights it', await animating(card('Original')))

// Reply drafts are per stream
await go('Work')
await card('Original').hover(); await card('Original').getByRole('button', { name: 'Reply' }).click()
await composerQuote.waitFor()
await go('Other')
check('switching streams hides that stream\'s pending reply', (await composerQuote.count()) === 0)
await go('Work')
check('pending reply restored when coming back', (await composerQuote.count()) === 1)
await composerQuote.getByRole('button', { name: 'Cancel reply' }).click()

// Deleting the original leaves a non-clickable placeholder
page.once('dialog', (d) => d.accept())
await card('Original').hover(); await card('Original').getByRole('button', { name: 'Delete' }).click()
await card('Original').waitFor({ state: 'detached' })
const orphan = card('First reply').locator('.quote')
check('deleted original shows placeholder quote', (await orphan.innerText()).includes('Original message was deleted') && (await orphan.locator('button.quote-body').count()) === 0)
await page.screenshot({ path: shotPath('v6-reply.png') })
check('no console errors', errors.length === 0, errors.join(' | '))
await finish(browser)
