import { BASE, checker, launch, shotPath } from './helpers.mjs'
import { devices } from 'playwright'
const { check, finish } = checker()
const browser = await launch()
const ctx = await browser.newContext({ ...devices['iPhone 13'] })
const page = await ctx.newPage()
await page.goto(BASE)
await page.getByRole('heading', { name: 'Inbox', level: 2 }).waitFor()
check('touch emulation reports coarse pointer', await page.evaluate(() => matchMedia('(pointer: coarse)').matches))
const c = page.getByLabel('Write to Inbox')
await c.fill('first line')
await c.press('Enter')
await c.type('second line')
await page.waitForTimeout(150)
check('Enter inserted a newline instead of saving', (await page.locator('.msg').count()) === 0 && (await c.inputValue()) === 'first line\nsecond line')
check('composer hint omits Enter-to-save', (await page.locator('.composer .hint').innerText()) === 'Markdown supported')
await page.getByRole('button', { name: 'Save' }).tap()
await page.locator('.msg').waitFor()
check('send button saves', (await page.locator('.msg .md').innerText()) === 'first line\nsecond line')
check('composer cleared', (await c.inputValue()) === '')
const card = page.locator('.msg').first()
check('touch shows one More button instead of an icon row', (await card.getByRole('button', { name: 'More actions' }).count()) === 1 && (await card.getByRole('button', { name: 'Edit' }).count()) === 0)
await card.getByRole('button', { name: 'More actions' }).tap()
const sheet = page.locator('dialog.sheet')
await sheet.waitFor()
check('sheet lists labelled actions with large rows', (await sheet.locator('.sheet-item').count()) >= 6 && (await sheet.locator('.sheet-item').first().evaluate((el) => el.getBoundingClientRect().height)) >= 48)
await page.screenshot({ path: shotPath('touch-sheet.png') })
await sheet.getByRole('button', { name: 'Edit' }).tap()
await sheet.waitFor({ state: 'detached' })
const e = card.getByLabel('Edit message')
await e.press('End'); await e.press('Enter'); await e.type('third line')
await page.waitForTimeout(150)
check('editor: Enter inserts newline', (await e.inputValue()) === 'first line\nsecond line\nthird line')
check('editor hint omits Enter-to-save', (await card.locator('.hint').innerText()) === 'Markdown supported')
await card.getByRole('button', { name: 'Save' }).tap()
await card.locator('time', { hasText: 'edited' }).waitFor()
check('editor save button records a version', (await card.locator('.md').innerText()).endsWith('third line'))
await e.waitFor({ state: 'detached' })
await card.getByRole('button', { name: 'More actions' }).tap()
await sheet.waitFor()
await sheet.getByRole('button', { name: 'Cancel' }).tap()
await sheet.waitFor({ state: 'detached' })
check('sheet Cancel closes without acting', (await card.getByLabel('Edit message').count()) === 0)
await card.getByRole('button', { name: 'More actions' }).tap()
await sheet.getByRole('button', { name: 'Edit' }).tap()
await card.getByLabel('Edit message').press('Escape')
check('editor: Escape still cancels', (await card.getByLabel('Edit message').count()) === 0)
await finish(browser)
