import { BASE, checker, launch } from './helpers.mjs'
const { check, finish } = checker()
const browser = await launch()
const page = await (await browser.newContext({ viewport: { width: 1000, height: 600 } })).newPage()
await page.goto(BASE)
const c = page.getByLabel('Write to Inbox')
await c.fill('short'); await c.press('Enter'); await page.locator('.msg').waitFor()
const lines = Array.from({ length: 40 }, (_, i) => `line ${i + 1}`).join('\n')
await c.fill(lines)
await page.waitForTimeout(100)
const m = await c.evaluate((el) => ({ h: el.clientHeight, sh: el.scrollHeight, inner: window.innerHeight }))
check('composer stops at the cap and scrolls inside', m.h <= 322 && m.h >= 300 && m.sh > m.h + 50, JSON.stringify(m))
check('pane does not need to scroll', await page.locator('.main').evaluate((el) => el.scrollHeight <= el.clientHeight + 1))
await c.press('Enter')
await page.waitForFunction(() => document.querySelectorAll('.msg').length === 2)
const long = page.locator('.msg', { has: page.locator('.msg-text', { hasText: 'line 40' }) })
await long.locator('.clamp.overflowing').waitFor()
const boxH = () => long.locator('.clamp-box').evaluate((el) => el.clientHeight)
check('long message is clamped to the same cap', (await boxH()) <= 322 && (await boxH()) >= 300, String(await boxH()))
check('clamped message offers Show more', (await long.locator('.clamp-btn').innerText()).trim() === 'Show more')
check('short message has no toggle', (await page.locator('.msg', { hasText: 'short' }).locator('.clamp-btn').count()) === 0)
await long.locator('.clamp-btn').click()
await page.waitForFunction(() => document.querySelector('.clamp.expanded'))
check('Show more expands fully', (await boxH()) > 600 && (await long.locator('.clamp-btn').innerText()).trim() === 'Show less')
await long.locator('.clamp-btn').click()
await page.waitForFunction(() => !document.querySelector('.clamp.expanded'))
check('Show less collapses again', (await boxH()) <= 322)
await long.hover(); await long.getByRole('button', { name: 'Edit' }).click()
const e = page.getByLabel('Edit message')
await page.waitForTimeout(100)
const em = await e.evaluate((el) => ({ h: el.clientHeight, sh: el.scrollHeight }))
check('inline editor is capped and scrolls inside', em.h <= 322 && em.h >= 300 && em.sh > em.h + 50, JSON.stringify(em))
await e.press('Escape')
await long.locator('.clamp-btn').click()
await page.waitForFunction(() => document.querySelector('.clamp.expanded'))
await long.hover(); await long.getByRole('button', { name: 'Edit' }).click()
const e2 = page.getByLabel('Edit message'); await e2.press('End'); await e2.type(' more'); await e2.press('Enter')
await long.locator('time', { hasText: 'edited' }).waitFor()
check('expanded state survives edit and save', (await long.locator('.clamp.expanded').count()) === 1 && (await boxH()) > 600)
await finish(browser)
