// Smoke test for the lab. Needs the dev server: `npm run dev`, then `node lab/check.mjs [base]`.
import { checker, launch, shotPath } from '../e2e/helpers.mjs'

const BASE = process.argv[2] ?? 'http://localhost:5173'
const MOD = process.platform === 'darwin' ? 'Meta' : 'Control'
const DOC_START = process.platform === 'darwin' ? 'Meta+ArrowUp' : 'Control+Home'
const DOC_END = process.platform === 'darwin' ? 'Meta+ArrowDown' : 'Control+End'
const { check, finish } = checker()
const browser = await launch()
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message)); page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()) })
const log = () => page.locator('.lab-log li').evaluateAll((els) => els.map((e) => `${e.querySelector('.lab-log-kind').textContent}:${e.querySelector('.lab-log-title').textContent}`))
const waitLog = (n) => page.waitForFunction((n) => document.querySelectorAll('.lab-log li').length >= n, n, { timeout: 5000 }).then(() => true, () => false)
// The DOM only holds what is near the viewport, so the checks read the notes themselves.
const texts = () => page.evaluate(() => window.labStore.notes.map((n) => window.labStore.textOf(n.id)))
const firstLines = async () => (await texts()).map((t) => t.split('\n')[0].slice(0, 14)).join('|')
const activeNote = () => page.evaluate(() => document.activeElement?.closest('[data-note-id]')?.dataset.noteId ?? null)
const caretLine = () => page.evaluate(() => getSelection()?.focusNode?.parentElement?.closest('.cm-line')?.textContent ?? null)

await page.goto(BASE + '/lab/')
await page.locator('.lab-single .cm-content').waitFor()

// ---------------------------------------------------------------- A: one editor
await page.keyboard.press(DOC_START)
await page.keyboard.type('A1 ')
check('A: typing in the first note writes back that note alone', (await waitLog(1)) && (await log()).join('|').startsWith('saved:A1 Call the plumber') && (await log()).length === 1, (await log()).join('|'))
await page.keyboard.press('ArrowDown')
check('A: ArrowDown walks straight into the next note', (await caretLine()) === '## Standup', await caretLine())
await page.keyboard.press('End')
await page.keyboard.press('Home')
await page.keyboard.press('Backspace')
await page.keyboard.press('Backspace')
await page.keyboard.type('A2 ')
await waitLog(2)
check('A: Backspace at the start of a note stops there: no join, and the caret does not slip into the note above', (await texts()).length === 13 && (await firstLines()).startsWith('A1 Call the pl|A2 ## Standup|'), await firstLines())
await page.screenshot({ path: shotPath('lab-a.png') })
await page.keyboard.press('ArrowUp')
await page.keyboard.press('End')
await page.keyboard.press('Delete')
await page.keyboard.type(' A3')
check('A: Delete at the end of a note stops there too', (await texts())[0].endsWith('Friday A3') && (await texts())[1].startsWith('A2 ## Standup'), (await texts())[0])
await page.keyboard.press(`${MOD}+a`)
await page.keyboard.type('gone')
await waitLog(15)
check('A: replacing a selection that spans every note empties each note but keeps all of them', (await texts()).join('|') === 'gone' + '|'.repeat(12), JSON.stringify((await texts()).map((t) => t.length)))
await page.keyboard.press(`${MOD}+z`)
check('A: one undo brings every note back', (await firstLines()).startsWith('A1 Call the pl|A2 ## Standup|Idea: the inbo|') && (await texts())[4].startsWith('Groceries'), await firstLines())
await page.keyboard.press(DOC_START)
const n0 = (await log()).length
await page.keyboard.press(`${MOD}+Enter`)
await page.keyboard.press('Backspace')
await page.waitForTimeout(100)
check('A: Mod-Enter adds a note below and Backspace in the empty note removes it', (await log()).slice(0, (await log()).length - n0).map((l) => l.split(':')[0]).join(',') === 'deleted,created' && (await texts()).length === 13, (await log()).slice(0, 3).join('|'))

// ---------------------------------------------------------------- B: editor per note
await page.getByRole('button', { name: 'B · Editor per note' }).click()
await page.locator('.lab-editor .cm-content').first().waitFor()
await page.waitForFunction(() => document.activeElement?.closest('[data-note-id]'))
check('B: switching approach keeps the caret in the same note', (await activeNote()) === 's0', await activeNote())
await page.keyboard.press('End')
await page.keyboard.press('ArrowDown')
check('B: ArrowDown on the last line moves into the next note\'s editor', (await activeNote()) === 's1' && (await caretLine()) === 'A2 ## Standup', `${await activeNote()} ${await caretLine()}`)
await page.keyboard.press('ArrowUp')
check('B: ArrowUp on the first line moves back', (await activeNote()) === 's0')
await page.keyboard.press('End')
await page.keyboard.press('ArrowRight')
await page.keyboard.type('B1 ')
const savedB1 = await page.waitForFunction(() => [...document.querySelectorAll('.lab-log-title')].some((e) => e.textContent.startsWith('B1 A2 ## Standup')), null, { timeout: 5000 }).then(() => true, () => false)
check('B: ArrowRight at the end enters the next note, and typing writes back that note', savedB1 && (await texts())[1].startsWith('B1 A2 ## Standup') && (await texts())[0].endsWith('Friday A3'), (await log())[0])
for (let i = 0; i < 8; i++) await page.keyboard.press('ArrowDown')
check('B: holding ArrowDown keeps crossing notes', !['s0', 's1'].includes(await activeNote()), await activeNote())
const top = await page.locator('.lab-scroll').evaluate((el) => el.scrollTop)
await page.keyboard.press('PageDown')
await page.waitForTimeout(300)
await page.keyboard.press('PageDown')
await page.waitForTimeout(300)
check('B: Page Down scrolls the page and keeps a caret', (await page.locator('.lab-scroll').evaluate((el) => el.scrollTop)) > top + 400 && (await activeNote()) !== null, await activeNote())
await page.screenshot({ path: shotPath('lab-b.png') })
await page.keyboard.press(DOC_END)
await page.keyboard.press(DOC_END)
await page.waitForTimeout(300)
check('B: document-end twice lands in the last note', (await activeNote()) === 's11', await activeNote())

// ---------------------------------------------------------------- virtualization
await page.locator('.lab-bar select').first().selectOption('stress')
await page.locator('.lab-editor .cm-content').first().waitFor()
await page.waitForTimeout(500)
const mountedB = await page.locator('.lab-scroll .cm-editor').count()
check('B: 3,000 notes mount only the editors near the viewport', mountedB > 0 && mountedB < 200, String(mountedB))
await page.getByRole('button', { name: 'A · One editor' }).click()
await page.locator('.lab-single .cm-content').waitFor()
await page.waitForTimeout(300)
const linesA = await page.locator('.lab-single .cm-line').count()
check('A: 3,000 notes render only the lines near the viewport', linesA > 0 && linesA < 600, String(linesA))
await page.keyboard.press(DOC_END)
await page.keyboard.type('end')
await page.waitForFunction(() => document.querySelector('.lab-log-title')?.textContent.startsWith('3000 ·'), null, { timeout: 5000 }).catch(() => {})
check('A: an edit at the far end is still routed to the right note', ((await log())[0] ?? '').startsWith('saved:3000 ·'), (await log())[0])

check('no console errors', errors.length === 0, errors.join(' | '))
await finish(browser)
